#!/usr/bin/env pwsh
# Real-CLI verification against the actual `agy` binary, split into two
# tiers by what they need:
#
#   Tier 1 (no account auth needed -- confirmed empirically: `agy agent`
#   and `agy plugin validate` are pure local/offline commands): agents
#   generated by sync.ps1 are actually visible to agy, and every staged
#   plugin's structure (skills/agents/commands/mcpServers/hooks) parses
#   as valid input to the real loader, not just to this repo's own
#   assumptions about the schema. This tier needs only `agy` installed
#   (https://antigravity.google/docs/cli/getting-started) -- no login, no
#   API key.
#
#   Tier 2 (needs a real, authenticated session -- interactive login, or
#   GEMINI_API_KEY per antigravity.google/docs/cli/install, which the
#   docs confirm "never establishes an account session" and so needs no
#   browser): whether a repo-synced plugin's hook actually FIRES when
#   Antigravity's own hook engine handles a real tool call. Every test of
#   this anywhere in this effort so far invoked the hook script directly
#   by hand -- this tier is the only thing that closes that gap for real.
#
# If Tier 2 can't run here (no auth available), Tier 1 still runs to
# completion and reports real results -- worth doing regardless.
#
# This script is designed against agy v1.1.22's actual interface,
# confirmed by installing and running it directly (`agy agent`, `agy
# plugin validate`, `agy --help`) -- Tier 1 is proven correct against the
# real tool. Tier 2's headless prompt-matching (`agy -p ... --output-format
# json`) is designed against the documented interface but was NOT run
# against an authenticated session anywhere in this effort. If its output
# shape differs from what's matched below, read the raw output printed on
# failure/INFO rather than trusting the verdict blindly.

$ErrorActionPreference = "Stop"
$results = [ordered]@{}

function Write-Result($name, $status, $detail) {
    $script:results[$name] = @{ status = $status; detail = $detail }
    $marker = if ($status -eq "PASS") { "[PASS]" } elseif ($status -eq "FAIL") { "[FAIL]" } else { "[INFO]" }
    Write-Output "$marker $name -- $detail"
}

$agy = Get-Command agy -ErrorAction SilentlyContinue
if (-not $agy) {
    Write-Result "cli-present" "FAIL" "agy not found on PATH. Install per https://antigravity.google/docs/cli/getting-started, then re-run this script."
    exit 1
}
$agyVersion = (& agy --version 2>&1 | Out-String).Trim()
Write-Result "cli-present" "PASS" "agy found at $($agy.Source) ($agyVersion)"

Write-Output ""
Write-Output "--- Tier 1: structural checks (no account auth needed) ---"

# --- agents generated by sync.ps1 are visible to the real agent loader ---
$probeAgentDir = Join-Path $HOME ".gemini/config/agents"
$probeAgentFile = Get-ChildItem $probeAgentDir -Filter "*.md" -File -ErrorAction SilentlyContinue | Select-Object -First 1
if ($probeAgentFile) {
    $probeAgentName = [System.IO.Path]::GetFileNameWithoutExtension($probeAgentFile.Name)
    $agentListing = & agy agent 2>&1 | Out-String
    if ($agentListing -match [regex]::Escape($probeAgentName)) {
        Write-Result "agents-visible" "PASS" "Translated agent '$probeAgentName' (from ~/.gemini/config/agents/) is in agy's real agent listing -- ~/.gemini/config/agents/ is the correct path, no ~/.gemini/antigravity-cli/agents/ copy needed."
    } else {
        Write-Result "agents-visible" "FAIL" "Translated agent '$probeAgentName' was not in agy's own agent listing. Raw output: $agentListing"
    }
} else {
    Write-Result "agents-visible" "INFO" "No translated agent files found at $probeAgentDir to probe with -- run bootstrap/sync.ps1 first."
}

# --- every staged plugin actually validates against the real loader ---
$pluginsDir = Join-Path $HOME ".gemini/config/plugins"
if (Test-Path $pluginsDir) {
    $pluginDirs = Get-ChildItem $pluginsDir -Directory -ErrorAction SilentlyContinue
    if (-not $pluginDirs -or $pluginDirs.Count -eq 0) {
        Write-Result "plugins-validate" "INFO" "No plugins found at $pluginsDir -- run bootstrap/sync.ps1 first."
    } else {
        $badPlugins = @()
        foreach ($pd in $pluginDirs) {
            $out = & agy plugin validate $pd.FullName 2>&1 | Out-String
            if ($out -match "(?i)error") {
                $badPlugins += "$($pd.Name): $out"
            }
        }
        if ($badPlugins.Count -eq 0) {
            Write-Result "plugins-validate" "PASS" "All $($pluginDirs.Count) staged plugins pass 'agy plugin validate' -- skills/hooks/mcpServers all parse as valid input to the real loader."
        } else {
            Write-Result "plugins-validate" "FAIL" "$($badPlugins.Count) of $($pluginDirs.Count) plugins failed validation: $($badPlugins -join ' | ')"
        }
    }
} else {
    Write-Result "plugins-validate" "INFO" "No plugins directory found at $pluginsDir -- run bootstrap/sync.ps1 first."
}

Write-Output ""
Write-Output "--- Tier 2: live behavioral check (needs an authenticated agy session) ---"

# If GEMINI_API_KEY is set but modelProvider isn't configured, agy defaults
# to a full interactive OAuth browser flow and hangs/times out in a
# headless shell -- discovered empirically, not documented anywhere
# obvious. Setting this is harmless when a real account session already
# exists (agy prefers an existing login over the API key in that case,
# per its own docs).
$settingsPath = Join-Path $HOME ".gemini/antigravity-cli/settings.json"
if ($env:GEMINI_API_KEY -and -not (Test-Path $settingsPath)) {
    New-Item -ItemType Directory -Path (Split-Path -Parent $settingsPath) -Force | Out-Null
    '{"modelProvider": "gemini"}' | Set-Content -Path $settingsPath
}

$authProbe = & agy -p "reply with exactly: PONG" --output-format json 2>&1 | Out-String
if ($authProbe -match "authentication required") {
    Write-Result "cli-authenticated" "INFO" "agy is not authenticated in this shell -- Tier 2 (real hook-firing check) skipped. Run 'agy' interactively once, or set GEMINI_API_KEY (antigravity.google/docs/cli/install), then re-run this script for the rest."
    $failCount = @($results.Values | Where-Object { $_.status -eq "FAIL" }).Count
    if ($failCount -gt 0) { exit 1 } else { exit 0 }
} elseif ($LASTEXITCODE -ne 0) {
    # --output-format json doesn't surface HTTP-level detail on stdout/stderr
    # -- it only lands in agy's own log file, one per invocation. Check the
    # newest one for the specific signature rather than guessing from the
    # generic "Agent execution terminated" wrapper alone.
    $logDir = Join-Path $HOME ".gemini/antigravity-cli/log"
    $logDetail = ""
    if (Test-Path $logDir) {
        $latestLog = Get-ChildItem $logDir -Filter "*.log" -File -ErrorAction SilentlyContinue | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($latestLog) {
            $logDetail = (Select-String -Path $latestLog.FullName -Pattern "ACCESS_TOKEN_TYPE_UNSUPPORTED|401|UNAUTHENTICATED" -ErrorAction SilentlyContinue | Select-Object -Last 3 | ForEach-Object { $_.Line }) -join "; "
        }
    }
    if ($logDetail) {
        Write-Result "cli-authenticated" "FAIL" "agy reached the real Gemini API and the credential was rejected. If using GEMINI_API_KEY, confirm it's a genuine AI Studio key (https://aistudio.google.com/apikey, starts with AIzaSy) and not an OAuth/session token copied from somewhere else -- those aren't accepted here. Log detail: $logDetail"
    } else {
        Write-Result "cli-authenticated" "FAIL" "agy -p failed for an unrecognized reason. stdout/stderr: $authProbe -- check $logDir for the newest log file's detail rather than trusting this script's pattern-matching."
    }
    exit 1
}
Write-Result "cli-authenticated" "PASS" "headless probe responded"

# --- tool execution isn't blocked by an unrelated built-in hook ---
$toolProbe = & agy -p "Run the shell command: echo AGENT_EXTENSIONS_TOOLCHECK" --output-format json 2>&1 | Out-String
if ($toolProbe -notmatch "AGENT_EXTENSIONS_TOOLCHECK") {
    Write-Result "tool-execution" "FAIL" "A plain, unblocked shell command did not appear to execute -- something (possibly the googlecloudtools.datacloud_telemetry built-in hook seen earlier in this effort) may still be blocking the tool-execution pipeline before any repo-synced hook gets a chance to run. Raw output: $toolProbe"
    Write-Output ""; Write-Output "--- summary ---"
    foreach ($k in $results.Keys) { Write-Output "$k`: $($results[$k].status)" }
    exit 1
}
Write-Result "tool-execution" "PASS" "a plain shell command executed and its output came back through agy"

# --- write a temporary, distinctive hookify rule ---
$ruleDir = ".claude"
New-Item -ItemType Directory -Path $ruleDir -Force | Out-Null
$rulePath = Join-Path $ruleDir "hookify.agent-extensions-live-check.local.md"
@"
---
name: agent-extensions-live-check
enabled: true
event: bash
pattern: AGENT_EXTENSIONS_HOOK_MARKER_87234
action: block
---
Temporary rule written by bootstrap/verify-antigravity-live.ps1 to prove a
repo-synced hook fires through Antigravity's real hook engine. Safe to
delete by hand; this script removes it automatically when done.
"@ | Set-Content -Path $rulePath

try {
    $blockProbe = & agy -p "Run this exact shell command and tell me exactly what happened, including any denial or error message verbatim: echo AGENT_EXTENSIONS_HOOK_MARKER_87234" --output-format json 2>&1 | Out-String

    if ($blockProbe -match "AGENT_EXTENSIONS_HOOK_MARKER_87234" -and $blockProbe -notmatch "(?i)(denied|blocked|prevent)") {
        Write-Result "hook-fires-for-real" "FAIL" "The command that should have been blocked by hookify's rule appears to have run anyway. hookify's PreToolUse hook is NOT firing through Antigravity's real hook engine, even though it works correctly when invoked by hand (already proven in PR #2). Raw output: $blockProbe"
    } elseif ($blockProbe -match "(?i)(denied|blocked|prevent)") {
        Write-Result "hook-fires-for-real" "PASS" "The command was blocked -- hookify's PreToolUse hook fired for real through Antigravity's hook engine. This closes the one remaining open question in the whole agent-extensions completion effort."
    } else {
        Write-Result "hook-fires-for-real" "INFO" "Inconclusive -- neither a clear block nor a clear pass-through was detected in the output. Read it directly rather than trusting this script's pattern-matching: $blockProbe"
    }
} finally {
    Remove-Item -Path $rulePath -ErrorAction SilentlyContinue
}

Write-Output ""
Write-Output "--- summary ---"
foreach ($k in $results.Keys) {
    Write-Output "$k`: $($results[$k].status)"
}
if ($results.Values | Where-Object { $_.status -eq "FAIL" }) {
    exit 1
}
exit 0
