#!/usr/bin/env bash
# Real-CLI verification against the actual `agy` binary, split into two
# tiers by what they need:
#
#   Tier 1 (no account auth needed -- confirmed empirically: `agy agent`
#   and `agy plugin validate` are pure local/offline commands): agents
#   generated by sync.sh are actually visible to agy, and every staged
#   plugin's structure (skills/agents/commands/mcpServers/hooks) parses
#   as valid input to the real loader, not just to this repo's own
#   assumptions about the schema. This tier needs only `agy` installed
#   (https://antigravity.google/docs/cli/getting-started) -- no login, no
#   API key.
#
#   Tier 2 (needs a real, authenticated session -- interactive login, or
#   GEMINI_API_KEY per antigravity.google/docs/cli/install, which the
#   docs confirm "never establishes an account session" and so needs no
#   browser): whether a repo-synced plugin's hook actually FIRES when
#   Antigravity's own hook engine handles a real tool call. Every test of
#   this anywhere in this effort so far invoked the hook script directly
#   by hand -- this tier is the only thing that closes that gap for real.
#
# If Tier 2 can't run here (no auth available), Tier 1 still runs to
# completion and reports real results -- worth doing regardless.
#
# This script is designed against agy v1.1.22's actual interface,
# confirmed by installing and running it directly (`agy agent`, `agy
# plugin validate`, `agy --help`) -- Tier 1 is proven correct against the
# real tool. Tier 2's headless prompt-matching (`agy -p ... --output-format
# json`) is designed against the documented interface but was NOT run
# against an authenticated session anywhere in this effort. If its output
# shape differs from what's matched below, read the raw output printed on
# failure/INFO rather than trusting the verdict blindly.
set -uo pipefail

failed=0

result() {
  local name="$1" status="$2" detail="$3"
  local marker="[INFO]"
  [ "$status" = "PASS" ] && marker="[PASS]"
  [ "$status" = "FAIL" ] && { marker="[FAIL]"; failed=1; }
  echo "$marker $name -- $detail"
}

if ! command -v agy >/dev/null 2>&1; then
  result "cli-present" "FAIL" "agy not found on PATH. Install per https://antigravity.google/docs/cli/getting-started, then re-run this script."
  exit 1
fi
result "cli-present" "PASS" "agy found at $(command -v agy) ($(agy --version 2>&1))"

echo ""
echo "--- Tier 1: structural checks (no account auth needed) ---"

# --- agents generated by sync.sh are visible to the real agent loader ---
probe_agent_dir="$HOME/.gemini/config/agents"
probe_agent_file="$(find "$probe_agent_dir" -maxdepth 1 -name '*.md' -type f 2>/dev/null | head -1)"
if [ -n "$probe_agent_file" ]; then
  probe_agent_name="$(basename "$probe_agent_file" .md)"
  agent_listing="$(agy agent 2>&1)"
  if echo "$agent_listing" | grep -qF "$probe_agent_name"; then
    result "agents-visible" "PASS" "Translated agent '$probe_agent_name' (from ~/.gemini/config/agents/) is in agy's real agent listing -- ~/.gemini/config/agents/ is the correct path, no ~/.gemini/antigravity-cli/agents/ copy needed."
  else
    result "agents-visible" "FAIL" "Translated agent '$probe_agent_name' was not in agy's own agent listing. Raw output: $agent_listing"
  fi
else
  result "agents-visible" "INFO" "No translated agent files found at $probe_agent_dir to probe with -- run bootstrap/sync.sh first."
fi

# --- every staged plugin actually validates against the real loader ---
plugins_dir="$HOME/.gemini/config/plugins"
if [ -d "$plugins_dir" ]; then
  plugin_fail=0
  plugin_count=0
  bad_plugins=()
  for d in "$plugins_dir"/*/; do
    [ -d "$d" ] || continue
    plugin_count=$((plugin_count + 1))
    out="$(agy plugin validate "$d" 2>&1)"
    if echo "$out" | grep -qi "error"; then
      plugin_fail=$((plugin_fail + 1))
      bad_plugins+=("$(basename "$d"): $out")
    fi
  done
  if [ "$plugin_count" -eq 0 ]; then
    result "plugins-validate" "INFO" "No plugins found at $plugins_dir -- run bootstrap/sync.sh first."
  elif [ "$plugin_fail" -eq 0 ]; then
    result "plugins-validate" "PASS" "All $plugin_count staged plugins pass 'agy plugin validate' -- skills/hooks/mcpServers all parse as valid input to the real loader."
  else
    result "plugins-validate" "FAIL" "$plugin_fail of $plugin_count plugins failed validation: $(printf '%s | ' "${bad_plugins[@]}")"
  fi
else
  result "plugins-validate" "INFO" "No plugins directory found at $plugins_dir -- run bootstrap/sync.sh first."
fi

echo ""
echo "--- Tier 2: live behavioral check (needs an authenticated agy session) ---"

# If GEMINI_API_KEY is set but modelProvider isn't configured, agy defaults
# to a full interactive OAuth browser flow and hangs/times out in a headless
# shell -- discovered empirically, not documented anywhere obvious. Setting
# this is harmless when a real account session already exists (agy prefers
# an existing login over the API key in that case, per its own docs).
settings_path="$HOME/.gemini/antigravity-cli/settings.json"
if [ -n "${GEMINI_API_KEY:-}" ] && [ ! -f "$settings_path" ]; then
  mkdir -p "$(dirname "$settings_path")"
  echo '{"modelProvider": "gemini"}' > "$settings_path"
fi

auth_probe="$(agy -p "reply with exactly: PONG" --output-format json 2>&1)"
auth_exit=$?
if echo "$auth_probe" | grep -qi "authentication required"; then
  result "cli-authenticated" "INFO" "agy is not authenticated in this shell -- Tier 2 (real hook-firing check) skipped. Run 'agy' interactively once, or set GEMINI_API_KEY (antigravity.google/docs/cli/install), then re-run this script for the rest."
  exit $failed
elif [ $auth_exit -ne 0 ]; then
  # --output-format json doesn't surface HTTP-level detail on stdout/stderr
  # -- it only lands in agy's own log file, one per invocation. Check the
  # newest one for the specific signature rather than guessing from the
  # generic "Agent execution terminated" wrapper alone.
  log_dir="$HOME/.gemini/antigravity-cli/log"
  log_detail=""
  if [ -d "$log_dir" ]; then
    latest_log="$(ls -t "$log_dir"/*.log 2>/dev/null | head -1)"
    [ -n "$latest_log" ] && log_detail="$(grep -iE "ACCESS_TOKEN_TYPE_UNSUPPORTED|401|UNAUTHENTICATED" "$latest_log" 2>/dev/null | tail -3)"
  fi
  if [ -n "$log_detail" ]; then
    result "cli-authenticated" "FAIL" "agy reached the real Gemini API and the credential was rejected. If using GEMINI_API_KEY, confirm it's a genuine AI Studio key (https://aistudio.google.com/apikey, starts with AIzaSy) and not an OAuth/session token copied from somewhere else -- those aren't accepted here. Log detail: $log_detail"
  else
    result "cli-authenticated" "FAIL" "agy -p failed for an unrecognized reason. stdout/stderr: $auth_probe -- check $log_dir for the newest log file's detail rather than trusting this script's pattern-matching."
  fi
  exit 1
fi
result "cli-authenticated" "PASS" "headless probe responded"

# --- Step 2: tool execution isn't blocked by an unrelated built-in hook ---
tool_probe="$(agy -p "Run the shell command: echo AGENT_EXTENSIONS_TOOLCHECK" --output-format json --dangerously-skip-permissions 2>&1)"
if ! echo "$tool_probe" | grep -q "AGENT_EXTENSIONS_TOOLCHECK"; then
  result "tool-execution" "FAIL" "A plain, unblocked shell command did not appear to execute -- something (possibly the googlecloudtools.datacloud_telemetry built-in hook seen earlier in this effort) may still be blocking the tool-execution pipeline before any repo-synced hook gets a chance to run. Raw output: $tool_probe"
  exit $failed
fi
result "tool-execution" "PASS" "a plain shell command executed and its output came back through agy"

# --- write a temporary, distinctive hookify rule ---
mkdir -p .claude
rule_path=".claude/hookify.agent-extensions-live-check.local.md"
cat > "$rule_path" <<'EOF'
---
name: agent-extensions-live-check
enabled: true
event: bash
pattern: AGENT_EXTENSIONS_HOOK_MARKER_87234
action: block
---
Temporary rule written by bootstrap/verify-antigravity-live.sh to prove a
repo-synced hook fires through Antigravity's real hook engine. Safe to
delete by hand; this script removes it automatically when done.
EOF
cleanup() { rm -f "$rule_path"; }
trap cleanup EXIT

# --- Step 4: ask agy to run the exact command that rule should block, for real ---
block_probe="$(agy -p "Run this exact shell command and tell me exactly what happened, including any denial or error message verbatim: echo AGENT_EXTENSIONS_HOOK_MARKER_87234" --output-format json --dangerously-skip-permissions 2>&1)"

# --- Step 5: interpret the result ---
if echo "$block_probe" | grep -q "AGENT_EXTENSIONS_HOOK_MARKER_87234" && ! echo "$block_probe" | grep -qiE "denied|blocked|prevent|hook"; then
  result "hook-fires-for-real" "FAIL" "The command that should have been blocked by hookify's rule appears to have run anyway. hookify's PreToolUse hook is NOT firing through Antigravity's real hook engine, even though it works correctly when invoked by hand (already proven in PR #2). Raw output: $block_probe"
elif echo "$block_probe" | grep -qiE "denied|blocked|prevent|hook"; then
  result "hook-fires-for-real" "PASS" "The command was blocked -- hookify's PreToolUse hook fired for real through Antigravity's hook engine. This closes the one remaining open question in the whole agent-extensions completion effort."
else
  result "hook-fires-for-real" "INFO" "Inconclusive -- neither a clear block nor a clear pass-through was detected in the output. Read it directly rather than trusting this script's pattern-matching: $block_probe"
fi

# --- Step 7: are translated agents actually visible to agy? ---
# Resolves the other open question from this effort: whether translated
# agents at ~/.gemini/config/agents/ (this repo's implemented target) are
# what Antigravity's CLI actually reads, or whether it needs a second copy
# under ~/.gemini/antigravity-cli/agents/ instead (a real directory on
# Kyle's machine, seen holding Antigravity's own built-in content, but
# never confirmed as an agent-loading path this repo also needs to write).
probe_agent_dir="$HOME/.gemini/config/agents"
probe_agent_file="$(find "$probe_agent_dir" -maxdepth 1 -name '*.md' -type f 2>/dev/null | head -1)"
if [ -n "$probe_agent_file" ]; then
  probe_agent_name="$(basename "$probe_agent_file" .md)"
  agent_probe="$(agy -p "List the names of your available custom agents or personas, exactly as they would be invoked." --output-format json --dangerously-skip-permissions 2>&1)"
  if echo "$agent_probe" | grep -qF "$probe_agent_name"; then
    result "agents-visible" "PASS" "Translated agent '$probe_agent_name' (from ~/.gemini/config/agents/) is visible to agy -- no second path needed."
  else
    result "agents-visible" "FAIL" "Translated agent '$probe_agent_name' was not found in agy's own agent listing. ~/.gemini/config/agents/ may not be what the CLI reads -- check whether it also needs writing to ~/.gemini/antigravity-cli/agents/ (sync.sh's ANTIGRAVITY_AGENTS_DIR can redirect there without a code change once confirmed). Raw output: $agent_probe"
  fi
else
  result "agents-visible" "INFO" "No translated agent files found at $probe_agent_dir to probe with -- run bootstrap/sync.sh first."
fi
exit $failed
